export { diceHandler } from "./dice"
export { quizHandler } from "./quiz"
export { reactionHandler, markGoSignal } from "./reaction"
export { tapTapHandler } from "./tap-tap"
export type { MiniGameHandler, RoundConfig, RoundWinnerResult } from "./types"
